name = "DynamicBounds"
uuid = "734901b1-590a-5f47-85e0-724a0ec3af09"
authors = ["Matthew Wilhelm <matthew.wilhelm@uconn.edu>"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
DynamicBoundsBase = "890bb398-7f8e-4565-ac8e-279ab2833f68"
DynamicBoundspODEsIneq = "8922cf73-a24a-4c59-b2b7-455e840875f0"

[compat]
DocStringExtensions = "~0.8"
DynamicBoundsBase = "0.1.0"
DynamicBoundspODEsIneq = "0.1"
julia = "~1.2, ~1.3, ~1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
